Remove installation step from travis script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -44,11 +44,11 @@ script:
  # 'ghc-prof-options: -auto-all'.
  - cabal check || true
  - cabal sdist
- - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}');
-   cd dist/;
-   if [ -f "$SRC_TGZ" ]; then
-      cabal install "$SRC_TGZ";
-   else
-      echo "expected '$SRC_TGZ' not found";
-      exit 1;
-   fi
+   #- export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}');
+   #cd dist/;
+   #if [ -f "$SRC_TGZ" ]; then
+   #cabal install "$SRC_TGZ";
+   #else
+   #echo "expected '$SRC_TGZ' not found";
+   #exit 1;
+   #fi
